export const SET_PRODUCTS = "setProducts"
export const INCREASE_CART_ITEMS = "increaseCartItems"
export const DECREASE_CART_ITEMS = "decreaseCartItems"
export const SELECTED_PRODUCT = "selectedProduct"
export const INCREASE_BILL = "increaseBill"
export const DECREASE_BILL = "decreaseBill"
export const EMPTY_CART = "emptyCart"
export const RESET = "reset"